# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='box_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='series',
            name='document_number',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='series',
            name='file_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='series',
            name='keywords',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='series',
            name='personnel',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='series',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='series',
            name='publication_series',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='research_notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='series',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='series',
            name='summary',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
