# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20161014_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='subseries_number',
            field=models.CharField(default='', max_length=3),
        ),
    ]
