# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_series_subseries_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='series',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='personnel',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='series',
            name='research_notes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='series',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
